version: "3.9"

services:
  pi-sense:
    build: .
    container_name: pi-sense
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
