const ROOT = import.meta.dir + '/../..';

function join(...parts: string[]) {
  return parts.join('/').replace(/\/+/g, '/');
}

export let cachedJS = '';
export let cachedCSS = '';

export async function generateSensorRegistry() {
  const glob = new Bun.Glob('sensors/*/sensor.tsx');
  const entries = [...glob.scanSync({ cwd: ROOT })].sort();

  const imports: string[] = [];
  const items: string[] = [];

  for (const entry of entries) {
    const slug = entry.match(/sensors\/([^/]+)\/sensor\.tsx/)?.[1];
    if (!slug) continue;
    if (!/^[a-z][a-z0-9-]*$/.test(slug)) {
      console.error(`Invalid sensor slug skipped: ${slug} (must be lowercase alphanumeric + hyphens)`);
      continue;
    }
    const varName = slug.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
    imports.push(`import ${varName} from '../../../${entry.replace(/\.tsx$/, '')}';`);
    imports.push(`import { config as ${varName}Config } from '../../../sensors/${slug}/config';`);
    items.push(`  { slug: '${slug}', Component: ${varName}, config: ${varName}Config },`);
  }

  const content = `// Auto-generated by builder.ts — do not edit manually
${imports.join('\n')}

import type { FunctionalComponent } from 'preact';
import type { SensorConfig } from '../types/sensor';

export interface SensorEntry {
  slug: string;
  Component: FunctionalComponent;
  config: SensorConfig;
}

const sensorRegistry: SensorEntry[] = [
${items.join('\n')}
];

export default sensorRegistry;
`;

  const srcDir = join(ROOT, 'src');
  try {
    if (await Bun.file(srcDir).stat().then(s => s.isDirectory()).catch(() => false)) {
      await Bun.write(join(ROOT, 'src/dashboard/generated/sensor-registry.ts'), content);
    }
  } catch {
    // Permission denied in production — file is only needed for dev rebuilds
  }
  console.log(`Generated sensor registry: ${entries.length} sensor(s) found`);
}

export async function buildApp() {
  await generateSensorRegistry();

  const result = await Bun.build({
    entrypoints: [join(ROOT, 'src/dashboard/index.tsx')],
    outdir: '/tmp/pi-sense-build',
    sourcemap: 'inline',
    target: 'browser',
  });

  if (result.success) {
    const js = result.outputs.find(o => o.type.startsWith('text/javascript'));
    const css = result.outputs.find(o => o.type.startsWith('text/css'));
    if (js) cachedJS = await js.text();
    if (css) cachedCSS = await css.text();
  } else {
    console.error('Build failed:', result.logs);
  }
}

export async function loadOrBuildApp() {
  const prebuiltJS = join(ROOT, 'dist', 'index.js');
  const prebuiltCSS = join(ROOT, 'dist', 'index.css');

  const jsExists = await Bun.file(prebuiltJS).exists();
  const cssExists = await Bun.file(prebuiltCSS).exists();

  if (jsExists && cssExists) {
    cachedJS = await Bun.file(prebuiltJS).text();
    cachedCSS = await Bun.file(prebuiltCSS).text();
    await generateSensorRegistry();
    console.log('Loaded pre-built frontend bundle from dist/');
  } else {
    await buildApp();
    console.log('Built frontend bundle from source');
  }
}

// Watcher functionality
let rebuildTimer: ReturnType<typeof setTimeout> | null = null;

function scheduleRebuild() {
  if (rebuildTimer) clearTimeout(rebuildTimer);
  rebuildTimer = setTimeout(async () => {
    rebuildTimer = null;
    console.log('Sensor files changed — rebuilding frontend...');
    await buildApp();
    console.log('Frontend rebuild complete');
  }, 300);
}

export function startWatching() {
  try {
    const { watchFile } = require('fs');
    const sensorsDir = join(ROOT, 'sensors');
    const srcDir = join(ROOT, 'src');

    watchFile(sensorsDir, { interval: 1000 }, (curr: any, prev: any) => {
      if (curr.mtimeMs !== prev.mtimeMs) scheduleRebuild();
    });

    watchFile(srcDir, { interval: 1000 }, (curr: any, prev: any) => {
      if (curr.mtimeMs !== prev.mtimeMs) scheduleRebuild();
    });

    console.log('Watching sensors/ and src/ for changes (polling every 1s)');
  } catch {
    console.log('Could not watch sensors/ and src/ — manual rebuild required');
  }
}
