// Auto-generated by builder.ts — do not edit manually
import waterVolume from '../sensors/water-volume/sensor';
import waterTank from '../sensors/water-tank/sensor';
import waterFlowLpm from '../sensors/water-flow-lpm/sensor';
import rawPulses from '../sensors/raw-pulses/sensor';

import type { FunctionalComponent } from 'preact';

export interface SensorEntry {
  slug: string;
  Component: FunctionalComponent;
}

const sensorRegistry: SensorEntry[] = [
  { slug: 'water-volume', Component: waterVolume },
  { slug: 'water-tank', Component: waterTank },
  { slug: 'water-flow-lpm', Component: waterFlowLpm },
  { slug: 'raw-pulses', Component: rawPulses },
];

export default sensorRegistry;
