// Auto-generated by server.ts — do not edit manually
import test3 from '../sensors/test-3/sensor';
import test2 from '../sensors/test-2/sensor';
import test from '../sensors/test/sensor';

import type { FunctionalComponent } from 'preact';

export interface SensorEntry {
  slug: string;
  Component: FunctionalComponent;
}

const sensorRegistry: SensorEntry[] = [
  { slug: 'test-3', Component: test3 },
  { slug: 'test-2', Component: test2 },
  { slug: 'test', Component: test },
];

export default sensorRegistry;
