// Auto-generated by server.ts — do not edit manually
import waterTank from '../sensors/water-tank/sensor';
import waterFlow from '../sensors/water-flow/sensor';

import type { FunctionalComponent } from 'preact';

export interface SensorEntry {
  slug: string;
  Component: FunctionalComponent;
}

const sensorRegistry: SensorEntry[] = [
  { slug: 'water-tank', Component: waterTank },
  { slug: 'water-flow', Component: waterFlow },
];

export default sensorRegistry;
